### ISSUE TITLE
nltk.txt missing application isn't working

### ISSUE THREAD

**Issue by abhishek-parashar** [kishan0725/The-Movie-Cinema#1] opened 2020-11-09 20:10 UTC
I have tried to deploy the application on heroku but failed multiple times. Kindly correct the bugs.
I am getting an invalid request error every time.

**Comment by kishan0725** [comment] 2020-11-10 03:20
There's nothing wrong with that error. There must be some other reason for the invalid request. There are several ways to track the issue. 

1. Check whether you've replaced the API key in both the lines in the recommend.js file. If you did and still getting invalid error, press 'ctrl+F5' in the browser (which clears the caches) and try again.
2. If that doesn't help you out, check the browser console. If you're getting a server side error (error code should be greater than or equal to 500), check your command prompt (windows) or terminal (linux and Mac). That should define the cause.

If nothing helps you, post your screenshots of the attempts. I'll try to help you as much as I can. 

Kindly close the issue once it gets resolved and before closing the issue, please tell us how you get it resolved. It might be helpful to those who are facing the same kind of issue. Thanks :)

**Comment by abhishek-parashar** [comment] 2020-11-10 05:23
Ya it solved the issue

**Comment by kishan0725** [comment] 2020-11-10 16:36
> Ya it solved the issue

Can you tell how did you get it resolved?

**Closed** 2020-11-28 09:07 UTC

**Comment by Sridharanraja** [comment] 2023-04-01 15:45
{"status_code":7,"status_message":"Invalid API key: You must be granted a valid key.","success":false}

**Comment by LakshmiPriya16678087** [comment] 2024-03-10 08:55
its showing invalid request could you please help me out even though after replacing my api key i tried ctrl+f5 but still not working
